services:
  - type: web
    name: hansol-car-rental
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --skip-generate --accept-data-loss && npx tsx prisma/seed.ts && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
